- stack/rest/src/test/java/org/apache/usergrid/rest/applications/assets/AssetResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/groups/GroupResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/users/UserResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/utils/TestUtils.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/utils/UserRepo.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/AbstractRestIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/ClientSetup.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/RestClient.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/ApplicationsResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/CollectionEndpoint.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/EntityEndpoint.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/NamedResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/OrganizationResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/RootResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/mgmt/ApplicationResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/mgmt/ManagementResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/mgmt/OrganizationResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/mgmt/TokenResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/ActivityEntity.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/ApiResponse.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/ChangePasswordEntity.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/Collection.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/Entity.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/QueryParameters.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/Token.java
- stack/rest/src/test/resources/usergrid-custom-test.properties
updating user test for new rest test framework
> Usergrid 291 user tests

- stack/launcher/src/main/java/org/apache/usergrid/launcher/App.java
Now we point the launcher to http://usergrid.incubator.apache.org/v101-portal-demo/ for the Portal
Related JIRA issue is here: https://issues.apache.org/jira/browse/USERGRID-315
> Point Launcher to a copy of Portal deployed to our project website.

- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/AndOrQueryTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/BadGrammarQueryTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/GeoPagingTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/MatrixQueryTests.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/OrderByTest.java
Updating query tests to work with new test framework
> Usergrid 303

- portal/js/global/help-service.js
- portal/js/global/ug-service.js
> Portal fixes

- stack/.editorconfig
for https://issues.apache.org/jira/browse/USERGRID-265
Comments welcome.
> Editorconfig file for the stack

- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/AndOrQueryTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/BadGrammarQueryTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/GeoPagingTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/OrderByTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/QueryTestBase.java
Needs to be reviewed. Don't merge yet.
> [USERGRID-320]Adding additional Query logic and result ordering tests

- stack/rest/src/test/java/org/apache/usergrid/rest/PartialUpdateTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/CollectionEndpoint.java
Needs to be reviewed. Don't merge yet.
> Updating PartialUpdateTest to work with the new REST test framework

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManagerFactory.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/HybridEntityManagerFactory.java
- stack/core/src/main/java/org/apache/usergrid/persistence/EntityManagerFactory.java
- stack/core/src/main/java/org/apache/usergrid/persistence/cassandra/EntityManagerFactoryImpl.java
- stack/core/src/test/java/org/apache/usergrid/persistence/cassandra/EntityManagerFactoryImplIT.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/EntityIndex.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsEntityIndexBatchImpl.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsEntityIndexImpl.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsIndexCache.java
- stack/rest/src/main/java/org/apache/usergrid/rest/applications/ApplicationResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/ApplicationDeleteTest.java
DO NOT MERGE. 
This work is ready for review.
Implements application delete as described here: https://issues.apache.org/jira/browse/USERGRID-312.
> USERGRID-312: Implement App Delete

- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/DuplicateNameIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/users/ConnectionResourceTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/management/organizations/AdminEmailEncodingIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/mgmt/ManagementResource.java
covers the following tickets:
https://issues.apache.org/jira/browse/USERGRID-331
https://issues.apache.org/jira/browse/USERGRID-327
> Rest test updates (for review, do not merge)

- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/model/Credentials.java
Fixes many tests in ApplicationResourceIT.
> Fix for key names in Credentials.java

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/core/src/main/java/org/apache/usergrid/persistence/EntityManager.java
- stack/core/src/main/java/org/apache/usergrid/persistence/cassandra/EntityManagerImpl.java
- stack/core/src/test/java/org/apache/usergrid/persistence/EntityManagerIT.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/EntityCollectionManager.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/FieldSet.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/cache/CachedEntityCollectionManager.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/impl/EntityCollectionManagerImpl.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/serialization/impl/FieldSetImpl.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/serialization/impl/MutableFieldSet.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/serialization/impl/UniqueValueSerializationStrategyImpl.java
- stack/corepersistence/collection/src/test/java/org/apache/usergrid/persistence/collection/EntityCollectionManagerIT.java
- stack/services/src/main/java/org/apache/usergrid/services/AbstractCollectionService.java
- stack/services/src/main/java/org/apache/usergrid/services/AbstractConnectionsService.java
DO NOT MERGE
pushed for review
https://issues.apache.org/jira/browse/USERGRID-396
> Usergrid 396

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpRelationManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/results/FilteringLoader.java
- stack/core/src/test/java/org/apache/usergrid/corepersistence/StaleIndexCleanupTest.java
> Usergrid 492

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpRelationManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/results/CollectionRefsVerifier.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/results/CollectionResultsLoaderFactoryImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/results/ConnectionRefsVerifier.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/results/ConnectionResultsLoaderFactoryImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/results/ElasticSearchQueryExecutor.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/results/QueryExecutor.java
- stack/core/src/main/java/org/apache/usergrid/persistence/MultiQueryIterator.java
- stack/core/src/main/java/org/apache/usergrid/persistence/Results.java
- stack/core/src/main/java/org/apache/usergrid/persistence/cassandra/QueryProcessorImpl.java
- stack/core/src/test/java/org/apache/usergrid/persistence/PathQueryIT.java
- stack/core/src/test/resources/log4j.properties
- stack/corepersistence/graph/src/test/java/org/apache/usergrid/persistence/graph/GraphManagerIT.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/IndexFig.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/BufferQueueInMemoryImpl.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsIndexBufferConsumerImpl.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/query/Query.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/utils/ListUtils.java
- stack/pom.xml
- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
Fixes issue with paging connections and collections
> Usergrid 511

- stack/rest/src/main/java/org/apache/usergrid/rest/applications/ServiceResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/assets/AssetResourceIT.java
Fix for https://issues.apache.org/jira/browse/USERGRID-530 plus a test.
> Deleting a connection to an Asset should not delete the Asset's data

- stack/core/src/main/java/org/apache/usergrid/corepersistence/ApplicationIdCacheImpl.java
- stack/core/src/test/java/org/apache/usergrid/persistence/cassandra/EntityManagerFactoryImplIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/ApplicationCreateTest.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/ApplicationDeleteTest.java
The fix is to lookup applications via unique value rather than query.
https://issues.apache.org/jira/browse/USERGRID-491
https://issues.apache.org/jira/browse/USERGRID-533
> Lookup applications using unique value instead of using query

- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/ApplicationResourceIT.java
Now only one test case fails in ApplicationResourceIT. Ignored couple of testcases which tests html response as we have problems with jsp and embedded tomcat 7.
Raised https://issues.apache.org/jira/browse/USERGRID-566 for the failed testcase.
> [USERGRID-497] - fixes for ApplicationResourceIT unit tests

- stack/tools/src/main/java/org/apache/usergrid/tools/ExportAdmins.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ImportAdmins.java
https://issues.apache.org/jira/browse/USERGRID-548
> Export import tool

- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/IndexFig.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsEntityIndexImpl.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsIndexBufferConsumerImpl.java
> Added elastic search timeout to search calls.

- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
Fix to ensure that local Admin Users created by SSO / external tokens get at least one organization.
Should have been part of USERGRID-575
> SSO / external tokens Admin User create fix

- stack/core/src/main/java/org/apache/usergrid/metrics/MetricsFactory.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
Adds metrics for:
- Count number of validated Admin Tokens
- Count number of rejected Admin Tokens
- Count number of new local Admin Users created
- Time processing time of /externaltokens method
Tested locally with Graphite.
For USERGRID-576
https://issues.apache.org/jira/browse/USERGRID-576
> Add metrics reporting to Usergrid SSO endpoint /externaltokens

- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
Portal needs /management/me to work when central SSO is enabled.
> Allow /management/me calls when central SSO is enabled.

- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
A couple of small fixes:
1) user's created in the SSO client system are activated
2) fix and simplify only superuser can login to SSO client system logic
> central SSO fixes

- stack/config/src/main/resources/usergrid-default.properties
- stack/rest/pom.xml
- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
Adds connection pool for HTTP client connections from SSO client system to SSO central.
> HTTP client connection pool for SSO token validation calls

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpRelationManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpWalker.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/EventBuilderImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/util/CpNamingUtils.java
- stack/core/src/main/java/org/apache/usergrid/persistence/AbstractEntity.java
- stack/core/src/main/java/org/apache/usergrid/persistence/EntityManager.java
- stack/core/src/main/java/org/apache/usergrid/persistence/EntityRef.java
- stack/core/src/main/java/org/apache/usergrid/persistence/MultiQueryIterator.java
- stack/core/src/main/java/org/apache/usergrid/persistence/SimpleCollectionRef.java
- stack/core/src/main/java/org/apache/usergrid/persistence/SimpleEntityRef.java
- stack/core/src/main/java/org/apache/usergrid/persistence/SimpleRoleRef.java
- stack/core/src/main/java/org/apache/usergrid/persistence/cassandra/ConnectionRefImpl.java
- stack/core/src/test/java/org/apache/usergrid/utils/EdgeTestUtils.java
- stack/corepersistence/graph/src/main/java/org/apache/usergrid/persistence/graph/impl/stage/NodeDeleteListenerImpl.java
- stack/services/src/main/java/org/apache/usergrid/services/AbstractService.java
Fixes issues with compaction on edge delete not firing
Fixes issue with connection meta data on importing entities.
> Usergrid 685

- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/ReIndexRequestBuilderImpl.java
- stack/rest/src/main/java/org/apache/usergrid/rest/IndexResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/security/SecuredResourceFilterFactory.java
- stack/rest/src/test/java/org/apache/usergrid/rest/IndexResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/management/ManagementResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/AbstractRestIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/endpoints/NamedResource.java
Added testing compatibility in rest test framework for index tests. (i.e adding a call for basic auth )
Added debugging for finding out if you are a superuser or not.
Added test for rebuilding endpoint and ignored previous unused test as fixing and adding tests for that should be a separate issue.
> [USERGRID-613] Fixed errors with running index endpoint.

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManagerFactory.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/util/CpNamingUtils.java
- stack/core/src/main/java/org/apache/usergrid/persistence/EntityManagerFactory.java
- stack/core/src/test/java/org/apache/usergrid/persistence/cassandra/EntityManagerFactoryImplIT.java
- stack/corepersistence/graph/src/test/java/org/apache/usergrid/persistence/graph/GraphManagerIT.java
Fixes app restore and cleans up timestamp naming conventions
> Usergrid 688

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpRelationManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/migration/AppInfoMigrationPlugin.java
- stack/services/src/test/java/org/apache/usergrid/corepersistence/migration/AppInfoMigrationPluginTest.java
Fixes bug in test assertion for incorrect count
Fixes bug with indexing on adding to collection
> Fixes bugs in migration with edge existence checks

- stack/rest/src/test/java/org/apache/usergrid/rest/applications/ApplicationResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource2point0/ClientSetup.java
- stack/services/src/main/java/org/apache/usergrid/security/shiro/Realm.java
- stack/services/src/main/java/org/apache/usergrid/security/shiro/utils/SubjectUtils.java
Also added additional test. 
Additional details below:
https://issues.apache.org/jira/browse/USERGRID-670
> Added ability for application client resources to be accepted.

- stack/rest/pom.xml
> Introduce a version number in the WAR file name for USERGRID-758

- stack/tools/src/main/java/org/apache/usergrid/tools/ExportAdmins.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ImportAdmins.java
Couple more fixes from testing:
1. only export credentials dictionary because it is all we need for admins, 
2. use em.get() instead of em.getRef() because it is more reliably.
> Couple small import/export fixes

- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AmazonAsyncEventService.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/QueueScope.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/impl/QueueScopeImpl.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/impl/SNSQueueManagerImpl.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/util/AmazonNotificationUtils.java
- stack/corepersistence/queue/src/test/java/org/apache/usergrid/persistence/queue/QueueManagerTest.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/NotificationsService.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/QueueListener.java
- stack/services/src/main/java/org/apache/usergrid/services/queues/QueueListener.java
Ensure all queues are subscribed to the multi-region SNS topics with appropriate permissions.  Topic/queue creation covered back to synchronous SNS client, leaving message send still using the async client.
> USERGRID-681 and USERGRID-798

- stack/core/src/main/java/org/apache/usergrid/persistence/Results.java
- stack/corepersistence/common/src/main/java/org/apache/usergrid/persistence/core/rx/RxSchedulerFig.java
- stack/services/src/main/java/org/apache/usergrid/services/AbstractService.java
Allows us to import entities in parallel, drastically increasing response times
> Import entities parallel

- stack/core/pom.xml
- stack/pom.xml
- stack/tools/pom.xml
- stack/tools/src/main/java/org/apache/usergrid/tools/ExportApp.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ExportDataCreator.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ExportingToolBase.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ToolBase.java
- stack/tools/src/main/resources/log4j.properties
- stack/tools/src/test/java/org/apache/usergrid/tools/ExportAppTest.java
https://issues.apache.org/jira/browse/USERGRID-788
> New ExportApp tool, using RxJava

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/util/CpEntityMapUtils.java
- stack/core/src/main/java/org/apache/usergrid/persistence/Query.java
- stack/core/src/main/java/org/apache/usergrid/persistence/entities/Notification.java
- stack/corepersistence/common/src/test/java/org/apache/usergrid/persistence/core/rx/OrderedMergeTest.java
- stack/corepersistence/model/pom.xml
- stack/corepersistence/model/src/main/java/org/apache/usergrid/persistence/model/field/FieldTypeName.java
- stack/corepersistence/model/src/main/java/org/apache/usergrid/persistence/model/field/SerializedObjectField.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsIndexBufferConsumerImpl.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/NotificationsService.java
add string field serialization
guava serialization was broken
> USERGRID-878 add string field serialization

- stack/core/src/main/java/org/apache/usergrid/corepersistence/util/CpEntityMapUtils.java
- stack/core/src/main/java/org/apache/usergrid/persistence/Schema.java
- stack/core/src/test/java/org/apache/usergrid/persistence/GeoIT.java
- stack/corepersistence/model/src/main/java/org/apache/usergrid/persistence/model/collection/SchemaManager.java
- stack/corepersistence/model/src/main/java/org/apache/usergrid/persistence/model/entity/EntityToMapConverter.java
- stack/corepersistence/model/src/main/java/org/apache/usergrid/persistence/model/entity/MapToEntityConverter.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EntityMappingParser.java
- stack/corepersistence/queryindex/src/test/java/org/apache/usergrid/persistence/index/impl/EntityToMapConverterTest.java
removed core converter, only in model now. 
location fields: convert to lat lon for ES otherwise its latitude longitude, used to use lat/lon only for storage  which is not expected in api returns.  so eliminate the return conversion.
> move to single map converter codebase.  

- stack/pom.xml
https://java.net/jira/browse/JERSEY-2632 details the the error that was here https://issues.apache.org/jira/browse/USERGRID-740
> Added USERGRID-740 fix to two-dot-o

- stack/core/src/main/java/org/apache/usergrid/persistence/cassandra/QueryProcessorImpl.java
- stack/core/src/test/java/org/apache/usergrid/persistence/GeoIT.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsEntityIndexImpl.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsQueryVistor.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/query/Query.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/query/tree/QueryVisitor.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/GeoPagingTest.java
https://issues.apache.org/jira/browse/USERGRID-460
> Added fixes to do distance ordered by queries.

- stack/config/src/main/resources/usergrid-default.properties
- stack/config/src/test/resources/usergrid-test.properties
- stack/core/src/main/java/org/apache/usergrid/count/AbstractBatcher.java
- stack/core/src/main/resources/usergrid-core-context.xml
- stack/core/src/test/java/org/apache/usergrid/persistence/CounterIT.java
> Usergrid 907 2.1

- stack/core/src/main/java/org/apache/usergrid/persistence/cassandra/EntityManagerImpl.java
- stack/core/src/main/java/org/apache/usergrid/persistence/cassandra/RelationManagerImpl.java
Fixes issue and add idempotent write into collection membership on property updates
> Fixes issue

- stack/config/src/main/resources/usergrid-default.properties
- stack/core/src/main/resources/usergrid-core-context.xml
Enable setting the following values for hector:
- cassandraThriftSocketTimeout
- useSocketKeepalive
Enabled HectorLockManager
> Add hector settings

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpRelationManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AmazonAsyncEventService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/InMemoryAsyncEventService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/ReIndexServiceImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/migration/DeDupConnectionDataMigration.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/pipeline/read/search/CandidateEntityFilter.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/pipeline/read/search/CandidateIdFilter.java
- stack/corepersistence/common/src/test/java/org/apache/usergrid/persistence/core/rx/ExceptionBehaviorTest.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/IndexFig.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsIndexProducerImpl.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/migration/EsIndexMappingMigrationPlugin.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/impl/QueueManagerFactoryImpl.java
- stack/rest/src/main/java/org/apache/usergrid/rest/ApplicationsResource.java
- stack/services/src/main/java/org/apache/usergrid/management/AppInfoMigrationPlugin.java
- stack/services/src/main/java/org/apache/usergrid/services/AbstractConnectionsService.java
change subscribe methodology where necessary
> change subscribe implementations

- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AmazonAsyncEventService.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/QueueFig.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/util/AmazonNotificationUtils.java
changed observable to java 8 stream. 
added exception handling for empty sets, 1 case needs to be ignored
> remove observable

- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AmazonAsyncEventService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/model/ElasticsearchIndexEvent.java
- stack/corepersistence/common/src/main/java/org/apache/usergrid/persistence/core/astyanax/CassandraConfig.java
- stack/corepersistence/common/src/main/java/org/apache/usergrid/persistence/core/astyanax/CassandraConfigImpl.java
- stack/corepersistence/map/src/main/java/org/apache/usergrid/persistence/map/impl/MapSerializationImpl.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/impl/SNSQueueManagerImpl.java
Changes our ES writes in the following way.
1) Events are queued in the same region
2) Events are processed in the same region
3) Batches are then persisted as a JSON body to the map
4) Events are sent to the topic
5) Each region processes the event.
> Usergrid 1048

- stack/core/src/main/java/org/apache/usergrid/persistence/CredentialsInfo.java
- stack/rest/src/main/java/org/apache/usergrid/rest/applications/users/UserResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/users/UserResourceIT.java
- stack/services/src/main/java/org/apache/usergrid/management/ManagementService.java
- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
Cherry picks branch from USERGRID-1079-1x into this branch, also adds PUT functionality, and tests the password GET + PUT works correctly
> Usergrid 1079 2x

- stack/services/pom.xml
remove exclusion from jackson dependencies
> remove exclusion

- stack/rest/src/main/java/org/apache/usergrid/rest/filters/MeteringFilter.java
- stack/rest/src/main/java/org/apache/usergrid/rest/filters/TracingFilter.java
- stack/rest/src/main/java/org/apache/usergrid/rest/security/CrossOriginRequestFilter.java
Fix annotations so that CORS and tracing filters work, and add JIRA issue for the TODO on the Metering Filter.
> Fix filter annotations

- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AmazonAsyncEventService.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/DeIndexOperation.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/IndexingUtils.java
- stack/corepersistence/queryindex/src/test/java/org/apache/usergrid/persistence/index/impl/IndexingUtilsTest.java
add method to invert the parsing of doc id to app id
add method to instantiate entityindexs for a indexoperationmanager
> fix alias issues

- stack/rest/src/main/java/org/apache/usergrid/rest/applications/users/UsersResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/exceptions/DuplicateUniquePropertyExistsExceptionMapper.java
- stack/tools/src/main/java/org/apache/usergrid/tools/CollectionUserFix.java
To be used when usergrid contains users are returned from queries but not directly referenced by their usernames.
> User collection fix

- stack/rest/src/main/java/org/apache/usergrid/rest/applications/users/UsersResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/exceptions/DuplicateUniquePropertyExistsExceptionMapper.java
- stack/tools/src/main/java/org/apache/usergrid/tools/CollectionUserFix.java
- stack/tools/src/main/java/org/apache/usergrid/tools/UniqueIndexCleanup.java
- stack/tools/src/test/java/org/apache/usergrid/tools/UniqueIndexCleanupTest.java
also includes usercollection fix.
> Usergrid 1076

- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/groups/GroupResourceIT.java
Details are here: https://issues.apache.org/jira/browse/USERGRID-1119
> Fix for USERGRID-1119 which tests the private group activities use case.

- stack/rest/src/test/java/org/apache/usergrid/rest/applications/ApplicationResourceIT.java
Details at https://issues.apache.org/jira/browse/USERGRID-1106
> Fix for broken ApplicationResourceIT test

- stack/rest/src/test/java/org/apache/usergrid/rest/management/AdminUsersIT.java
This PR re-enables 6 previously ignored or commented out tests in AdminUsersIT.
Work done for JIRA issue USERGRID-1115 
https://issues.apache.org/jira/browse/USERGRID-1115
> Fix ignored tests in AdminUsersIT

- stack/core/src/main/java/org/apache/usergrid/persistence/entities/Notification.java
- stack/core/src/main/java/org/apache/usergrid/persistence/entities/Notifier.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/LocalQueueManager.java
- stack/pom.xml
- stack/services/pom.xml
- stack/services/src/main/java/org/apache/usergrid/services/notifications/NotificationsService.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/ProviderAdapter.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/QueueListener.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/TestAdapter.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/apns/APNsAdapter.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/gcm/GCMAdapter.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/impl/ApplicationQueueManagerImpl.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/wns/WNSAdapter.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/AbstractServiceNotificationIT.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/apns/MockSuccessfulProviderAdapter.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/apns/NotificationsServiceIT.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/gcm/MockSuccessfulProviderAdapter.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/gcm/NotificationsServiceIT.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/wns/WNSAdapterTest.java
Updated to latest GCM library and support "priority" in push notification entities.  Enhanced QueueListener thread naming and shutdown logic.  Fixed all GCM push notification tests.  Fixed matrix queries in notifications service.
> USERGRID-1182, USERGRID-1113

- stack/core/src/test/java/org/apache/usergrid/persistence/GeoIT.java
Created test to address possible issue noted here
https://issues.apache.org/jira/browse/USERGRID-1012
> Usergrid 1012

- sdks/ios/README.md
This PR addresses https://issues.apache.org/jira/browse/USERGRID-1237
> USERGRID-1237 - Update links in iOS SDK README

- sdks/android/src/main/java/org/apache/usergrid/android/sdk/UGClient.java
User DefaultURLConnectionFactory is not URLConnectionFactory is specified.
use urlConnectionFactory.openConnection(urlAsString) instead of new URL(urlAsString).openConnection();
> USERGRID-1206 UGClient does not use URLConnectionFactory.

- stack/rest/src/main/java/org/apache/usergrid/rest/management/users/UsersResource.java
> USERGRID-1188: return error rather than 204 when email not provided

- stack/rest/src/main/java/org/apache/usergrid/rest/management/organizations/applications/ApplicationResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/ApplicationDeleteIT.java
Change from application_identifier to confirm_application_identifier, and adjusted tests.
> Better name for application delete protection parameter 

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/CollectionsResourceIT.java
This is ready for review?  Have any ideas for additional testing?
For more information: https://issues.apache.org/jira/browse/USERGRID-1278
> Disable indexing per Entity type

- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
Fixes USERGRID-1280
https://issues.apache.org/jira/browse/USERGRID-1280
> Invalidate ShiroCache when admin user added to org

- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/TaskManager.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/gcm/NotificationsServiceIT.java
Added example of the counters. 
Included dave's changes because they haven't synced yet for some reason.
> Counter with test

- stack/config/src/main/resources/usergrid-default.properties
- stack/services/src/main/java/org/apache/usergrid/services/ServiceManager.java
And there are two configuration properties to control how often and how many times to retry.
> Service manager's init() method now retries if unable to get application

- stack/services/src/main/java/org/apache/usergrid/security/shiro/ShiroCache.java
The original cache key logic did not work well when the principal was not a user (e.g. application or organization credentials) and because of that it was possible for a guest user to use the same cache key as an application or organization, and possibly gain the same level of access.
> Better Shiro permission cache key logic

- stack/services/src/main/java/org/apache/usergrid/security/shiro/ShiroCache.java
- Wrap the if-else logic in a try catch block
- Log instances where key type is unknown
- Only throw Shiro CacheException
> Improvements to error handling in cache key generation

- stack/core/src/main/java/org/apache/usergrid/persistence/entities/Notification.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/CollectionsResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource/endpoints/CollectionEndpoint.java
- stack/services/src/main/java/org/apache/usergrid/services/notifications/impl/ApplicationQueueManagerImpl.java
- stack/services/src/test/java/org/apache/usergrid/services/notifications/AbstractServiceNotificationIT.java
Fix for class cast exceptions when migrating for notifications.
> Release class cast exception

- stack/corepersistence/queryindex/src/test/java/org/apache/usergrid/persistence/index/impl/EntityIndexTest.java
- stack/pom.xml
- stack/query-validator/pom.xml
- stack/query-validator/src/test/java/org/apache/usergrid/query/validator/AbstractQueryIT.java
- stack/query-validator/src/test/java/org/apache/usergrid/query/validator/QueryITSuite.java
- stack/query-validator/src/test/java/org/apache/usergrid/query/validator/users/UserQueryIT.java
- stack/query-validator/src/test/resources/usergrid-test-context.xml
- stack/rest/src/test/java/org/apache/usergrid/rest/ITSetup.java
READY FOR MERGE
This work is for https://issues.apache.org/jira/browse/USERGRID-221
Changes to POM and to test infrastructure so that the Query Validator will build and run properly. 
Two problems persist:
1) some queries now require "order by created desc" when they did not before in UG 1.0
2) five tests had to be ignored because they fail, but they did not before in UG 1.0
(they are failing due to this bug https://issues.apache.org/jira/browse/USERGRID-1314)
> Fixes Query Validator, but had to ignore 5 of the tests.

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManagerFactory.java
- stack/core/src/test/java/org/apache/usergrid/corepersistence/index/IndexServiceTest.java
- stack/corepersistence/actorsystem/src/main/java/org/apache/usergrid/persistence/actorsystem/ActorSystemManager.java
- stack/corepersistence/actorsystem/src/main/java/org/apache/usergrid/persistence/actorsystem/ActorSystemManagerImpl.java
- stack/corepersistence/actorsystem/src/main/java/org/apache/usergrid/persistence/actorsystem/RouterProducer.java
- stack/corepersistence/actorsystem/src/test/java/org/apache/usergrid/persistence/actorsystem/ActorServiceServiceTest.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/uniquevalues/UniqueValuesServiceImpl.java
- stack/corepersistence/collection/src/test/java/org/apache/usergrid/persistence/collection/AbstractUniqueValueTest.java
So that ActorSystemManager can set them up instead of exposing a registerMessageType() method.
> require RouterProducers to provide list of the Message Types 

- stack/rest/src/main/java/org/apache/usergrid/rest/exceptions/AbstractExceptionMapper.java
- stack/rest/src/main/java/org/apache/usergrid/rest/exceptions/PasswordPolicyViolationExceptionMapper.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/users/PermissionsResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/users/UserResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/management/AdminUsersIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/management/ManagementResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/management/RegistrationIT.java
- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
- stack/services/src/main/java/org/apache/usergrid/security/PasswordPolicy.java
- stack/services/src/main/java/org/apache/usergrid/security/PasswordPolicyFig.java
- stack/services/src/main/java/org/apache/usergrid/security/PasswordPolicyImpl.java
- stack/services/src/main/java/org/apache/usergrid/services/exceptions/PasswordPolicyViolationException.java
- stack/services/src/main/java/org/apache/usergrid/services/guice/ServiceModuleImpl.java
- stack/services/src/test/java/org/apache/usergrid/security/PasswordPolicyTest.java
- stack/services/src/test/java/org/apache/usergrid/security/PasswordPolicyTestFig.java
Work done for USERGRID-1320 "Configurable Password Policy"
https://issues.apache.org/jira/browse/USERGRID-1320
> Configurable Password Policy and 5 supporting JUnit tests.

- stack/corepersistence/queue/pom.xml
- stack/pom.xml
- stack/rest/pom.xml
- stack/services/pom.xml
- stack/services/src/main/java/org/apache/usergrid/services/assets/data/GoogleBinaryStore.java
This reverts commit ae14dc911e8fa7e97cbba839e7700159d5b2be42.
> Revert "Remove dependency conflicts"

- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/ReIndexService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/ReIndexServiceImpl.java
- stack/core/src/test/java/org/apache/usergrid/persistence/RebuildIndexTest.java
- stack/pom.xml
- stack/rest/src/test/java/org/apache/usergrid/rest/IndexResourceIT.java
- stack/services/src/test/java/org/apache/usergrid/NewOrgAppAdminRule.java
- stack/services/src/test/java/org/apache/usergrid/management/OrganizationConfigIT.java
- stack/services/src/test/java/org/apache/usergrid/management/export/ExportServiceIT.java
The tests were broken due to changes in 8913e43 and due to a couple of other issues.
The reindex status functionality was also broken. Fixed that
> Fixed tests for index rebuild

- stack/tools/src/main/java/org/apache/usergrid/tools/Export.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ExportingToolBase.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ToolBase.java
Export tool now works in parallel for multiple collections
Exports can be resumed from last exported edge
Export is substantially faster due to parallel processing
Connection fetching is optimzed
Export now creates multiple dirs for apps and collections
> Revamped Export code to be more efficient

- stack/README.md
Type mistake in stack README.md file
> stack README link type fixed

- stack/tools/src/main/java/org/apache/usergrid/tools/UniqueValueRepairer.java
Jira link : https://jira.apache.org/jira/browse/USERGRID-1352
> USERGRID-1352 : Tool to bulk repair Unique Value entities. 

- stack/corepersistence/actorsystem/src/main/java/org/apache/usergrid/persistence/actorsystem/ActorSystemManager.java
- stack/corepersistence/actorsystem/src/main/java/org/apache/usergrid/persistence/actorsystem/ActorSystemManagerImpl.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/uniquevalues/UniqueValueActor.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/uniquevalues/UniqueValuesFig.java
Fixes for
https://issues.apache.org/jira/projects/USERGRID/issues/USERGRID-1355
https://issues.apache.org/jira/projects/USERGRID/issues/USERGRID-1354
> Akka cluster issues fixes and mods

- stack/tools/src/main/java/org/apache/usergrid/tools/Export.java
This will establish relationship between entity and dictionary.
> Added entity id and type to dictionary object in export.

- stack/Jenkinsfile
- stack/pom.xml
https://issues.apache.org/jira/browse/USERGRID-1359
> USERGRID-1359 : Create the ASF Jenkins build pipeline for Usergrid Stack

- .travis.yml
- stack/Jenkinsfile
Rewrote Jenkins pipeline to fix flaky C* behavior
Added travis pipeline
> Fix build pipeline
