apache/usergrid

- docs/usage.md
Minor fix to include the link to the Perl module in usage.md.
> Documentation fix - link to Perl module

- sdks/html5-javascript/lib/modules/Client.js
With this function developers can login as admin by adding the following code after initializing the usergrid client.
client.adminlogin("superuser","superuser");
related improvement in jira = https://issues.apache.org/jira/browse/USERGRID-167
> Adding admin login function to Client.js

- stack/rest/src/main/java/org/apache/usergrid/rest/ApiResponse.java
- stack/rest/src/main/java/org/apache/usergrid/rest/exceptions/AbstractExceptionMapper.java
- stack/rest/src/main/java/org/apache/usergrid/rest/exceptions/UncaughtException.java
Added UncaughtException to handle uncaught errors. It creates a time uuid and it is set as error id in error response. 
Sample response, 
> {"error":"uncaught","timestamp":1428023297834,"duration":1,"error_description":"Internal Server Error","exception":"org.apache.usergrid.rest.exceptions.UncaughtException","error_id":"e97cf251-d99d-11e4-8c2e-4eff6b02c98b"}
> [USERGRID-538] - improve error response for uncaught errors

- stack/corepersistence/collection/src/test/java/org/apache/usergrid/persistence/collection/util/EntityHelper.java
Build error:
[ERROR] /home/app/stack/corepersistence/collection/src/test/java/org/apache/usergrid/persistence/collection/util/EntityHelper.java:[79,8] error: unmappable character for encoding ASCII
Fixed by removal of spurious character.
> Removed spurious character

- stack/config/src/main/resources/usergrid-default.properties
- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/organizations/OrganizationsResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/users/UserResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/users/UsersResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/management/ManagementResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/management/users/MUUserResourceIT.java
Or be activated or be confirmed... all that should happen via Usergrid Central.
> Ensure that when external token validation is enabled, Admin Users cannot sign-up

- docs/file-storage-configuration.md
- stack/pom.xml
- stack/services/pom.xml
- stack/services/src/main/java/org/apache/usergrid/services/assets/data/AwsSdkS3BinaryStore.java
See https://issues.apache.org/jira/browse/USERGRID-579
This adds the AwsSdkS3BinaryStore class, the old S3BinaryStore class will still be available. 
AwsSdkS3BinaryStore has several advantages :
- upload files up to 50GB
- support of V4 signing process
- lower network latency when a regionName is defined
I tested it with an 1.2 GB file so far and checked all md5 checksums to be sure everything is fine.
Only the deleting is not working but I believe that the bug is not in the class. It appears that the binaryStore.delete() method is never called. I think it has something to do with this ticket https://issues.apache.org/jira/browse/USERGRID-530
I will make further investigations on it.
PS : My ICLA was approved.
> 579 - alternative to the S3BinaryStore class

- stack/services/pom.xml
Remove Jackson 2 dependency that snuck in with new AWS S3 store because it breaks the rest tests.
> Remove Jackson 2 dependency

- stack/config/src/main/resources/usergrid-default.properties
- stack/pom.xml
- stack/rest/src/main/java/org/apache/usergrid/rest/applications/ServiceResource.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/assets/AssetResourceIT.java
- stack/services/src/main/java/org/apache/usergrid/services/assets/data/S3BinaryStore.java
This PR upgrades from to JClouds 1.7.1 and because JClouds no longer supports async calls to AWS, I had to change code in S3BinaryStore to create a thread for large uploads (i.e. larger than 5mb).
This PR also includes changes from the branch sso-conn-pool, which adds a connection pool for Central SSO HTTPClient calls. See the PR #245 if you want to review those changes separately.
> Upgrade JClouds, add connection pool for Central SSO

- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ImportAdmins.java
- stack/tools/src/test/java/org/apache/usergrid/tools/ExportImportAdminsTest.java
- ExportAdmins now does not halt when getOrganizationsForAdminUser() has uniqueness violation
- ImportAdmins logic now only creates an organization if it does not already exist
- Additional test assertion to cover managementService.getAdminUsersForOrganization()
> Small fixes to Admin import/export tool based on results of testing

- stack/tools/src/main/java/org/apache/usergrid/tools/ExportAdmins.java
Use multiple threads to read data from Cassandra and one thread to write that data to the two output files. How it works:
- In main thread we query for IDs of all admin users, add each ID to read queue.
- Read-queue workers read admin user data, add data to write queue.
- One write-queue worker reads data writes to file.
Depending on number of threads you specify with the new -readThreads parameter performance is increased by as much as 10X.
> Improve Export Admins performance.

- stack/tools/src/main/java/org/apache/usergrid/tools/ExportAdmins.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ImportAdmins.java
- stack/tools/src/main/resources/log4j.properties
A bunch of changes and improvements made while testing export and import of Admin Users.
1) Removed code that handled connections and collections because we do not need them for Admin User import/export and because they were causing errors.
2) In ExportAdmins I introduced a user to orgs mapping because the getOrganzationsForAdminUser() is not 100% reliable on some Userid systems.
3) Made many logging changes and the addition of (atomic integer) counters to give better feedback about import/export progress.
> ImportAdmins and ExportAdmins fixes

- stack/tools/src/main/java/org/apache/usergrid/tools/ExportAdmins.java
- stack/tools/src/main/java/org/apache/usergrid/tools/ImportAdmins.java
- stack/tools/src/main/resources/log4j.properties
- stack/tools/src/test/java/org/apache/usergrid/tools/ExportImportAdminsTest.java
- stack/tools/src/test/resources/admin-user-metadata.usergrid-management.1433331614293.json
- stack/tools/src/test/resources/admin-users.usergrid-management.1433331614293.json
ImportAdmins will now merge duplicate user accounts and give the merged account a union of the orgs in the duplicates. ExportAdmins no longer exports users with no organizations or credentials. Both tools now use more consistent logging.
> Additional fixes to ExportAdmins & ImportAdmins

- stack/core/src/main/java/org/apache/usergrid/utils/JsonUtils.java
- stack/tools/src/main/resources/toolsApplicationContext.xml
- stack/tools/src/test/java/org/apache/usergrid/tools/ExportAppTest.java
Tools should depend on Services not REST, JsonUtils should chill out on the warnings and ExportAppTest now needs at least 5 writeThreads to keep up with Usergrid reads (not sure why).
> ExportAppTest fixes

- stack/rest/src/main/java/org/apache/usergrid/rest/ApiResponse.java
- stack/rest/src/test/java/org/apache/usergrid/rest/ApiResponseTest.java
Added a set of params to be ignored in response. Following params will be ignored. 
client_id, client_secret, password, username, access_token, client_credentials, fb_access_token,
fq_access_token, ping_access_token, token
Please let me know if this is okay, I'll make the change on master as well and send another PR.
> [USERGRID-572] - ignore sensitive params from QP in response params

- stack/rest/src/main/java/org/apache/usergrid/rest/applications/ServiceResource.java
- stack/services/src/main/java/org/apache/usergrid/services/AbstractService.java
- stack/services/src/main/java/org/apache/usergrid/services/ServiceManager.java
- stack/services/src/main/java/org/apache/usergrid/services/ServiceRequest.java
connections=all (or no connections parameter): both connections and connecting metadata retrieved
connections=none: neither connections nor connecting metadata retrieved
connections=in: only connecting metadata retrieved
connections=out: only connections metadata retrieved
Will add tests in separate PR.
> USERGRID-918: add query parameter to limit checks for connections

- stack/core/src/main/java/org/apache/usergrid/corepersistence/util/CpNamingUtils.java
- stack/rest/src/main/java/org/apache/usergrid/rest/ApiResponse.java
- stack/rest/src/main/java/org/apache/usergrid/rest/applications/ServiceResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/organizations/OrganizationResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/organizations/OrganizationsResource.java
- stack/services/src/main/java/org/apache/usergrid/management/ManagementService.java
- stack/services/src/main/java/org/apache/usergrid/management/OrganizationConfig.java
- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
1. Add organization config GET and PUT.
2. Use default connections parameter stored in organization config (if it exists) for limiting connection reads when retrieving an entity/collection.
Todo:
1. Fix organization config GET and PUT so that it requires superuser access (required USERGRID-645).
2. Organization config info should be cached.
3. Tests.
> USERGRID-992: organization-level configuration

- stack/rest/src/main/java/org/apache/usergrid/rest/management/organizations/OrganizationResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/security/SecuredResourceFilterFactory.java
- stack/rest/src/main/java/org/apache/usergrid/rest/security/shiro/filters/BasicAuthSecurityFilter.java
- stack/services/src/main/java/org/apache/usergrid/security/shiro/Realm.java
1. Superuser access via token now works. Some code was checking for hardcoded string "sysadmin" -- superuser role is now "service-admin".
2. Superuser token should now be granted access to all orgs and apps.
3. Locked down org config GET/PUT to superusers only.
Basic auth superuser still does not have access to orgs/apps. Org config GET/PUT requires both org access to specified org and superuser access, so token must be used for org config.
> USERGRID-645: fix superuser access via token

- stack/Coverage.md
- stack/core/pom.xml
- stack/corepersistence/collection/pom.xml
- stack/corepersistence/graph/pom.xml
- stack/corepersistence/pom.xml
- stack/corepersistence/queryindex/pom.xml
- stack/pom.xml
- stack/test-utils/pom.xml
The Jacoco Maven plugin generates a separate jacoco.exec data file for each of our Maven modules and cannot produce a combined "master" report.  The plugin can generate an merged data file, but cannot easily create a merged report. So, we use the Maven plugin to produce the Jacoco data files, but we new a an Ant-task to merge the data files and produce a merged report. 
See the Coverage.md file for instructions on creating Javaco module and the master report.
https://issues.apache.org/jira/browse/USERGRID-1058
> For USERGRID-1058: Add ability to generate master Jacoco report for all stack modules

- stack/corepersistence/graph/src/test/java/org/apache/usergrid/persistence/graph/GraphManagerShardConsistencyIT.java
- stack/corepersistence/graph/src/test/java/org/apache/usergrid/persistence/graph/serialization/impl/shard/impl/ShardGroupDeletionImplTest.java
Fixes 2 bugs found during testing of mass deletes
> Usergrid 1052

- stack/Coverage.md
- stack/core/pom.xml
- stack/corepersistence/collection/pom.xml
- stack/corepersistence/common/pom.xml
- stack/corepersistence/graph/pom.xml
- stack/corepersistence/map/pom.xml
- stack/corepersistence/model/pom.xml
- stack/corepersistence/pom.xml
- stack/corepersistence/queryindex/pom.xml
- stack/corepersistence/queue/pom.xml
- stack/jacoco-pom.xml
- stack/pom.xml
- stack/rest/pom.xml
- stack/rest/src/main/java/org/apache/usergrid/rest/security/shiro/session/HttpRequestSessionManager.java
- stack/services/pom.xml
- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
- stack/test-utils/pom.xml
With this PR the Jacoco plugin is made optional and will only run when you specify the -Pjacoco argument.  This PR also fixes two problems 1) the Jacoco agent was being specific twice for some modules slowing down the build and 2) we were not invalidating the ShiroCache when an application is restored.
On my machine this saves about 2 minutes of build time (build is 14 minutes without Jacoco and 16 minutes with Jacoco turned on).
> Make Jacoco optional via Maven profile

- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AmazonAsyncEventService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AsyncEventService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/InMemoryAsyncEventService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/IndexProcessorFig.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/pipeline/read/traverse/AbstractReadGraphFilter.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/pipeline/read/traverse/ReadGraphCollectionFilter.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/pipeline/read/traverse/ReadGraphConnectionFilter.java
- stack/corepersistence/graph/src/main/java/org/apache/usergrid/persistence/graph/impl/stage/NodeDeleteListenerImpl.java
Also:
-set the default visibility timeout to 30 sec to account for systems under load 
-default # of consumers to 16
-remove schedulers.io subscription from node delete observable so we can use async scheduler higher up in code
> Change read repair to delete from c* and send de-index only event to all regions.

- stack/rest/src/main/java/org/apache/usergrid/rest/system/ConnectionResource.java
- stack/scripts/create_test_data.py
- stack/scripts/migrate_entity_data.py
- stack/scripts/multitenant_migrate.py
This PR adds a new multitenant_migrate.py script that can, if used correctly, migration a Usergrid 2.0 cluster with multiple "tenants" or organizations to Usergrid 2.1 format. See the comments in the header of the file for instructions on how to run.
Associated JIRA issue: https://issues.apache.org/jira/browse/USERGRID-1068
> First and untested stab at multi-tenant migration

- stack/tools/src/main/java/org/apache/usergrid/tools/DuplicateOrgRepair.java
Adding in Russo's new updateOrganizationUniqueIndex() to ensure that the keeper organization is the one that is in the unique name index.
> Add index repair to merge duplicates.

- sdks/nodejs/lib/usergrid.js
The `hasNextPage` method returned evaluation of its `_next` property,
which is either a string or null. Method documentation says it returns a
boolean value.
The result is now `_next` forced to boolean using `!!`.
> Update hasNextPage to return boolean

- stack/rest/src/main/java/org/apache/usergrid/rest/exceptions/ElasticsearchExecutionExceptionMapper.java
There is a specific error thrown back if elasticsearch cannot search or if the search queue is set to 0. Now it will return 503 service unavailable if we cannot execute the search against elasticsearch
> ElasticsearchException added so we return 503's if we don't do GETs.

- stack/core/src/main/java/org/apache/usergrid/corepersistence/ApplicationIdCache.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/ApplicationIdCacheImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManagerFactory.java
- stack/core/src/main/java/org/apache/usergrid/persistence/EntityManagerFactory.java
- stack/core/src/test/java/org/apache/usergrid/corepersistence/index/AsyncEventServiceImplTest.java
- stack/core/src/test/java/org/apache/usergrid/persistence/cassandra/EntityManagerFactoryImplIT.java
- stack/mongo-emulator/src/test/java/org/apache/usergrid/mongo/BasicMongoTest.java
- stack/mongo-emulator/src/test/java/org/apache/usergrid/mongo/MongoQueryTest.java
- stack/rest/src/main/java/org/apache/usergrid/rest/organizations/OrganizationResource.java
- stack/services/src/main/java/org/apache/usergrid/management/cassandra/ManagementServiceImpl.java
- stack/services/src/test/java/org/apache/usergrid/corepersistence/migration/AppInfoMigrationPluginTest.java
Fix for https://issues.apache.org/jira/browse/USERGRID-1277
The Application ID cache in CpEntityManagerFactoryImpl caches Optional<UUID> even when o.isPresent() is false. When there is a problem retrieving an application ID from Cassandra and the ID comes back as null, we cache that value and, until the cache entry expires 60 seconds later, the cache returns null for that application and Usergrid throws an NPE, server error 500, etc.
The cache logic should be simplified and we should cache UUIDs and not Optionals.
> Application ID cache should not cache Optionals

- stack/core/src/main/java/org/apache/usergrid/corepersistence/pipeline/read/search/CandidateEntityFilter.java
- stack/core/src/test/java/org/apache/usergrid/persistence/IndexIT.java
- stack/corepersistence/model/src/main/java/org/apache/usergrid/persistence/model/field/value/EntityObject.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/queries/SelectMappingsQueryTest.java
In Usergrid 2 the JSON data format returned for Queries with Select Mappings changed from an array of field values to an array of Entities, each with only the selected fields (plus normal UUID, type and metadata fields).
This PR adds support for nested fields in Queries with Select Mappings, and ensures that field names are preserved as-is but treated in a case-insensitive way.
> Support for nested fields in Query Select Mappings

- stack/config/src/main/resources/usergrid-default.properties
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManagerFactory.java
- stack/core/src/main/java/org/apache/usergrid/locking/LockManager.java
- stack/core/src/main/java/org/apache/usergrid/locking/cassandra/AstyanaxLockManagerImpl.java
- stack/core/src/main/java/org/apache/usergrid/locking/noop/NoOpLockManagerImpl.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/exception/CollectionRuntimeException.java
- stack/corepersistence/common/src/main/java/org/apache/usergrid/persistence/core/astyanax/CassandraCluster.java
- stack/corepersistence/common/src/main/java/org/apache/usergrid/persistence/core/astyanax/CassandraFig.java
- stack/services/src/main/java/org/apache/usergrid/services/ServiceManager.java
- stack/services/src/main/java/org/apache/usergrid/services/ServiceManagerFactory.java
Changes related to management app / startup logic
1) Lock Manager setup now happens in the EntityManagerFactory and is invoked as part  of the normal /database/setup process.
2) CpEntityManagerFactory now checks for the existence of the management app and will retry if it cannot be found, unless Usergrid has not yet been bootstrapped. It will log the root cause exception and a track trace. Max retries and interval are configurable.
3) CpEntityManagerFactory now keeps a "cache" of the latest fetched Management App object. EntityManager cache will update the cached Management App object whenever it is successfully fetched.
4) CpEntityManagerFactory's cache of EntityManagers will not cache bad EntityManagers, i.e. those that cannot fetch their own applications, or the application's name is …
> Improvements to management app / startup logic

- stack/rest/src/main/java/org/apache/usergrid/rest/applications/users/UserResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/applications/users/UsersResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/users/UserResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/management/users/UsersResource.java
- stack/rest/src/main/java/org/apache/usergrid/rest/security/SecuredResourceFilterFactory.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/SecurityIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/applications/collection/users/PermissionsResourceIT.java
- stack/rest/src/test/java/org/apache/usergrid/rest/test/resource/endpoints/NamedResource.java
- stack/services/src/main/java/org/apache/usergrid/security/shiro/principals/ApplicationUserPrincipal.java
Ensure that /org/app/users/me always works for logged in user, regardless of roles/permissions, also that it is impossible to create an app or admin user named 'me' (via post or put)
> /org/app/users/me and /users/me related fixes

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/EntityManagerFig.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AsyncEventService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AsyncEventServiceImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/EventBuilder.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/EventBuilderImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/model/DeIndexOldVersionsEvent.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/IndexService.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/IndexServiceImpl.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/EntityCollectionManager.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/impl/EntityCollectionManagerImpl.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/serialization/SerializationFig.java
- stack/corepersistence/collection/src/main/java/org/apache/usergrid/persistence/collection/serialization/impl/LogEntryIterator.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/EntityIndex.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/IndexFig.java
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/impl/EsEntityIndexImpl.java
- stack/corepersistence/queryindex/src/test/java/org/apache/usergrid/persistence/index/impl/EntityIndexTest.java
- Re-introduce a more efficient de-index upon entity delete and entity updates.  Remove the inefficient code as a safety measure so it can't be used again. 
- Add configurable delay after unique value read repair deletion as immediate creation may follow in code before Cassandra replicates the operation.
> USERGRID-1295 and USERGRID-1297

- sdks/dotnet/Usergrid.Sdk.IntegrationTests/BaseTest.cs
- sdks/dotnet/Usergrid.Sdk.IntegrationTests/EntityPagingTests.cs
- sdks/dotnet/Usergrid.Sdk.IntegrationTests/GroupTests.cs
- sdks/dotnet/Usergrid.Sdk.IntegrationTests/LoginTests.cs
- sdks/dotnet/Usergrid.Sdk.IntegrationTests/Usergrid.Sdk.IntegrationTests.dll.config
* Fixes https://issues.apache.org/jira/browse/USERGRID-1306
* Add a new apiUri configuration to the settings files that allow for running integration tests against something aside from http://api.usergrid.com
* If nothing is specified for this config or if it is missing, the default behavior of using http://api.usergrid.com is enforced
> Allow .NET Integration Tests to be run against any usergrid installation

- stack/core/src/main/java/org/apache/usergrid/batch/service/JobSchedulerService.java
- stack/core/src/main/java/org/apache/usergrid/mq/cassandra/CassandraMQUtils.java
A: doesn't flood the logs whenever we run a check for a job
B: tell us whenever it drives to get the queued.
> QueueLogging has been changed so that it

- stack/rest/src/test/java/org/apache/usergrid/rest/management/ExternalSSOEnabledIT.java
- stack/services/src/main/java/org/apache/usergrid/security/sso/ApigeeSSO2Provider.java
- stack/services/src/test/java/org/apache/usergrid/security/ApigeeSSO2ProviderIT.java
Review purposes only. Not certain that this is the right approach.
> If claims cannot be parsed, fetch new JWT token

- stack/core/src/main/java/org/apache/usergrid/corepersistence/CoreModule.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CpEntityManager.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/GuiceFactory.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AsyncIndexProvider.java
- stack/core/src/test/java/org/apache/usergrid/corepersistence/TestCoreModule.java
- stack/core/src/test/java/org/apache/usergrid/corepersistence/TestIndexModule.java
- stack/core/src/test/resources/usergrid-custom-test.properties
- stack/corepersistence/queryindex/src/main/java/org/apache/usergrid/persistence/index/guice/IndexModule.java
- stack/corepersistence/queryindex/src/test/java/org/apache/usergrid/persistence/index/guice/TestIndexModule.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/LegacyQueueManager.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/guice/QueueModule.java
- stack/corepersistence/queue/src/test/java/org/apache/usergrid/persistence/queue/TestModule.java
- stack/rest/src/test/resources/usergrid-custom-test.properties
- stack/services/src/test/resources/usergrid-custom-test.properties
Make it possible to configure either LOCAL, DISTRIBUTED or DISTRIBUTED_SNS queue; also: set Core tests to use DISTRIBUTED queue (i.e. Qakka).
> Configurable ElasticSearch indexing implementation

- stack/config/src/main/resources/usergrid-default.properties
- stack/core/src/main/java/org/apache/usergrid/corepersistence/CoreModule.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/asyncevents/AsyncEventServiceImpl.java
- stack/core/src/main/java/org/apache/usergrid/corepersistence/index/IndexProcessorFig.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/LegacyQueueFig.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/LegacyQueueManager.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/LegacyQueueScope.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/LocalQueueManager.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/guice/QueueModule.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/impl/LegacyQueueScopeImpl.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/impl/QakkaQueueManager.java
- stack/corepersistence/queue/src/main/java/org/apache/usergrid/persistence/queue/impl/SNSQueueManagerImpl.java
- stack/services/src/main/java/org/apache/usergrid/services/AbstractCollectionService.java
- stack/services/src/main/java/org/apache/usergrid/services/queues/ImportQueueManager.java
1. Add workers that move messages from dead letter queues back to the indexing and utility queues.
2. Change ERROR for DuplicateUniquePropertyExistsException to INFO. This happens when someone tries to create an entity with the same unique value as another entity, which is not an error that should be logged.
3. Add better logging when cluster region or region list has an invalid region.
> dead letter queue handling

- stack/rest/src/main/java/org/apache/usergrid/rest/management/ManagementResource.java
- stack/services/src/main/java/org/apache/usergrid/security/shiro/ShiroCache.java
Before this, if a user had multiple sessions with different tokens,
only one Principal was stored in the cache, with the first token. Now
every user session has a principal mapped to it in the cache
https://issues.apache.org/jira/browse/USERGRID-1353?filter=-1
> Fixed shiro cache to ensure 1:1 mapping between token and principal

- stack/tools/src/main/java/org/apache/usergrid/tools/Export.java
Enables configuring number of threads for fetching entities,
assets and entity members
This fixes issue USERGRID-1356
> Made entity export threads configurable

- stack/Jenkinsfile
- stack/core/src/test/java/org/apache/usergrid/persistence/CollectionDeleteTest.java
The test for CollectionDelete is failing on machines with more
processing power because the timestamp for the last to-be-deleted entry
and the next one ends up being the same. Added a sleep and also setup
non-boundary test scenarios and more logging.
Updated the Jenkins build to increase timeouts
> USERGRID-1348 : Fix failure for CollectionDeleteTest
